---
title: "Todays top songs"
format: 
  dashboard: 
    logo: "images/logo.png"
    orientation: columns
---

## Column {width="35%"}

Placeholder for col1

```{r, loadpackages}
#| echo: false
#| include: false
library(tidyverse)
library(httr2)
library(gt)
```

```{r, accesstoken}
#| echo: false
#| include: false
client_id = Sys.getenv("spotify_client")
client_secret = Sys.getenv("spotify_secret")

req_access_token <- request("https://accounts.spotify.com/api/token") |>
  req_method("POST") |>
  req_body_raw(
    paste0(
      "grant_type=client_credentials&client_id=",
      client_id,
      "&client_secret=",
      client_secret),
      "application/x-www-form-urlencoded"
  ) |>
  req_perform() |>
  resp_body_json()

spotify_access_token <- req_access_token$access_token
```

```{r, spotifyplaylist}
playlist <- request("https://api.spotify.com/v1/playlists/6bxc68SmD0XJ9tyPXDLnFq") |>
  req_method("GET") |>
  req_headers(Authorization = paste0("Bearer ", spotify_access_token)) |>
  req_perform() |>
  resp_body_json()

playlist_df <- data.frame(
  song_name = unlist(lapply(playlist$tracks$items, FUN = function(x) {x$track$name})),
  song_id = unlist(lapply(playlist$tracks$items, FUN = function(x) {x$track$id})),
  artist_name = unlist(lapply(playlist$tracks$items, FUN = function(item) {item$track$album$artists[[1]]$name})),
  album_art = unlist(lapply(playlist$tracks$items,FUN = function(item) {item$track$album$images[[1]]$url})),
  track_duration = unlist(lapply(playlist$tracks$items, FUN = function(item) {item$track$duration_ms})),
  popularity = unlist(lapply(playlist$tracks$items, FUN = function (item) {item$track$popularity}))
)
```

```{r, table}
playlist_df %>% 
  dplyr::select(album_art,song_name, artist_name, track_duration, popularity) %>% 
  mutate(track_duration = track_duration/60000) %>% 
  gt() %>% 
  cols_label(
    album_art = md("**Song**"),
    song_name = "",
    artist_name = md("**Artist**"),
    track_duration = html('<svg xmlns="http://www.w3.org/2000/svg" height="15" width="15" viewBox="0 0 512 512"><path fill="#ffffff" d="M256 0a256 256 0 1 1 0 512A256 256 0 1 1 256 0zM232 120l0 136c0 8 4 15.5 10.7 20l96 64c11 7.4 25.9 4.4 33.3-6.7s4.4-25.9-6.7-33.3L280 243.2 280 120c0-13.3-10.7-24-24-24s-24 10.7-24 24z"/></svg>'),
    popularity = md("**Popularity**")
  ) %>% 
  text_transform(
    fn = function(x) {
      web_image(url = x, height = 50)
    },
    locations = cells_body(columns = album_art)
  ) %>% 
  fmt_duration(columns = track_duration,
               input_units = "minutes",
               output_units = c("minutes", "seconds"),
               duration_style = "colon-sep") %>% 
  tab_options(
    table.font.color = "white",
    table.background.color = "#191414"
  )

```
## Column {width="65%"}

### Row {height="10%"}


```{r, sendtoojs}
#| echo: false
#| include: false
ojs_define(playlist_ojs = playlist_df)
```

```{ojs}
//| expandable: false

// Tranpose the data to  make it usable in ojs
top_hits = transpose(playlist_ojs)

// Create a dropdown menu of the songs
viewof songDropdown = Inputs.select(
  top_hits.map(d => d.song_name),
  {
    label: "Choose a song",
    unique: true
  }
)
```

### Row {height="70%"}

```{ojs}
//| expandable: false
html`<iframe class="custom-iframe" style="border-radius:12px; display: flex; justify-content: center; align-items: center;" 
  src=${`https://open.spotify.com/embed/track/${top_hits.find(song => song.song_name === songDropdown).song_id}?utm_source=generator&theme=0`} 
  width="100%" 
  height="352" 
  frameBorder="0" 
  allowfullscreen="" 
  allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" 
  loading="lazy">
</iframe>`
```

### Row {height="20%"}

Placeholder for col2, row3